# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6JkHs3jIUF-gSREqqgHc-v1IXOArxqs
"""

# Import necessary libraries for data manipulation, financial data fetching, and deep learning model building
import yfinance as yf  # Library to download historical market data from Yahoo! Finance
import pandas as pd  # Library for data manipulation and analysis, especially with DataFrames
import numpy as np  # Library for numerical operations, particularly useful for array manipulations
import pickle  # Library for serializing and deserializing Python object structures

# Import MinMaxScaler from scikit-learn for feature scaling
from sklearn.preprocessing import MinMaxScaler

# Import components from TensorFlow/Keras for building a Sequential neural network model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout  # LSTM for recurrent layers, Dense for output, Dropout for regularization

# Define the stock ticker symbol for which to download data
ticker = "AAPL"

# Download historical stock data for the specified ticker
data = yf.download(
    ticker,             # The ticker symbol (e.g., "AAPL" for Apple Inc.)
    period="2y",        # Download data for the last 2 years
    interval="1d"       # Use daily intervals (1 day per data point)
)

# --- Feature Engineering: Calculate Technical Indicators ---

# Calculate the 20-day Simple Moving Average (SMA)
# SMA helps to smooth out price data and identify trend direction.
data["SMA20"] = data["Close"].rolling(20).mean()

# Calculate the 20-day Exponential Moving Average (EMA)
# EMA gives more weight to recent prices, making it more responsive to new information.
data["EMA20"] = data["Close"].ewm(span=20).mean()

# Calculate the price change (delta) between consecutive 'Close' prices
delta = data["Close"].diff()

# Separate positive price changes (gains) and negative price changes (losses)
# clip(lower=0) sets all negative values to 0
gain = delta.clip(lower=0)
# -clip(upper=0) sets all positive values to 0 and makes losses positive
loss = -delta.clip(upper=0)

# Calculate the average gain and average loss over a 14-period window
avg_gain = gain.rolling(14).mean()
avg_loss = loss.rolling(14).mean()

# Calculate the Relative Strength (RS)
# RS is the ratio of average gain to average loss
rs = avg_gain / avg_loss

# Calculate the Relative Strength Index (RSI)
# RSI is a momentum oscillator that measures the speed and change of price movements.
# It ranges from 0 to 100, typically used to identify overbought or oversold conditions.
data["RSI"] = 100 - (100 / (1 + rs))

# Drop any rows that contain NaN values (e.g., from initial rolling calculations)
data.dropna(inplace=True)

# Select the features that will be used as input for the LSTM model
# 'Close' price, 'Volume', and the calculated technical indicators
features = data[["Close","Volume","SMA20","EMA20","RSI"]]

# --- Data Preprocessing for LSTM ---

# Initialize MinMaxScaler to scale features to a range between 0 and 1
# Scaling is crucial for neural networks to ensure stable and faster training.
scaler = MinMaxScaler()

# Fit the scaler to the features and transform them
scaled = scaler.fit_transform(features)

# Prepare input (X) and output (y) data for the LSTM model
# The LSTM will be trained to predict the next 'Close' price based on a sequence of past data.
X = []  # List to store input sequences
y = []  # List to store corresponding target 'Close' prices

window = 60  # Define the look-back window size (number of past days to consider)

# Create sequences of data for the LSTM model
# Each X entry will be a sequence of 'window' data points (features)
# Each y entry will be the 'Close' price of the day immediately following the sequence
for i in range(window, len(scaled)):
    X.append(scaled[i-window:i])  # Append a sequence of 'window' days' features
    y.append(scaled[i,0])         # Append the 'Close' price (first feature) of the (i+1)-th day

# Convert lists of sequences to NumPy arrays
X = np.array(X)  # Input data for the LSTM
y = np.array(y)  # Target data for the LSTM

# --- Build the LSTM Model ---

# Initialize a Sequential Keras model (a linear stack of layers)
model = Sequential()

# Add the first LSTM layer
# 64 units (neurons) in the LSTM layer
# return_sequences=True ensures that the output of this layer is a sequence, needed for stacking LSTMs
# input_shape specifies the shape of one input sample (window size, number of features)
model.add(
    LSTM(
        64,
        return_sequences=True,
        input_shape=(X.shape[1],X.shape[2])
    )
)

# Add a Dropout layer to prevent overfitting
# Dropout randomly sets a fraction of input units to 0 at each update during training, which helps prevent overfitting.
model.add(Dropout(0.2))

# Add a second LSTM layer
# This layer does not return sequences as it's followed by the output layer.
model.add(LSTM(64))

# Add the output Dense layer
# A single unit (neuron) for predicting a single value (the 'Close' price)
model.add(Dense(1))

# --- Compile and Train the Model ---

# Compile the model with an optimizer and a loss function
# optimizer="adam" is an efficient optimization algorithm.
# loss="mse" (Mean Squared Error) is a common loss function for regression tasks.
model.compile(
    optimizer="adam",
    loss="mse"
)

# Train the LSTM model
# X: Input features
# y: Target 'Close' prices
# epochs: Number of times to iterate over the entire training dataset
# batch_size: Number of samples per gradient update
model.fit(
    X,
    y,
    epochs=15,
    batch_size=32
)

# --- Save Model and Scaler ---

# Save the trained LSTM model to a file for future use
# The model architecture, weights, and training configuration are saved.
model.save("models/lstm_model.keras")

# Save the MinMaxScaler object
# It's crucial to save the scaler used for training to be able to inverse transform predictions
# back to the original price scale when making new predictions.
pickle.dump(
    scaler,
    open("models/scaler.pkl","wb")
)

