# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6JkHs3jIUF-gSREqqgHc-v1IXOArxqs
"""

"""
train_model.py
Run this ONCE locally to train and save models for all 10 stocks.
Then upload the models/ and scalers/ folders to your GitHub repo.

Usage:
    python train_model.py
"""

import os
import pickle
import numpy as np
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.layers import (
    Dense, LSTM, Dropout,
    MultiHeadAttention, LayerNormalization, GlobalAveragePooling1D
)

STOCKS = {
    "AAPL":  "Apple",
    "MSFT":  "Microsoft",
    "GOOGL": "Google",
    "AMZN":  "Amazon",
    "NVDA":  "NVIDIA",
    "TSLA":  "Tesla",
    "META":  "Meta",
    "BRK-B": "Berkshire",
    "JPM":   "JPMorgan",
    "V":     "Visa",
}

WINDOW   = 60
EPOCHS   = 20
BATCH    = 32
FEATURES = ["Close", "Volume", "SMA20", "EMA20", "RSI", "Upper", "Lower"]

os.makedirs("models",  exist_ok=True)
os.makedirs("scalers", exist_ok=True)


def add_indicators(data):
    data["SMA20"] = data["Close"].rolling(20).mean()
    data["EMA20"] = data["Close"].ewm(span=20).mean()
    delta         = data["Close"].diff()
    gain          = delta.clip(lower=0).rolling(14).mean()
    loss          = -delta.clip(upper=0).rolling(14).mean()
    rs            = gain / loss
    data["RSI"]   = 100 - (100 / (1 + rs))
    data["MA20"]  = data["Close"].rolling(20).mean()
    data["STD"]   = data["Close"].rolling(20).std()
    data["Upper"] = data["MA20"] + (2 * data["STD"])
    data["Lower"] = data["MA20"] - (2 * data["STD"])
    data.dropna(inplace=True)
    return data


def build_model(input_shape):
    inputs    = tf.keras.Input(shape=input_shape)
    attention = MultiHeadAttention(num_heads=4, key_dim=32)(inputs, inputs)
    x         = LayerNormalization()(inputs + attention)
    x         = LSTM(64, return_sequences=True)(x)
    x         = Dropout(0.2)(x)
    x         = GlobalAveragePooling1D()(x)
    outputs   = Dense(1)(x)
    model     = tf.keras.Model(inputs, outputs)
    model.compile(optimizer="adam", loss="mse")
    return model


for ticker, name in STOCKS.items():
    print(f"\n{'='*45}")
    print(f"  Training: {name} ({ticker})")
    print(f"{'='*45}")

    raw = yf.download(ticker, period="2y", interval="1d", progress=False)

    if raw is None or raw.empty:
        print(f"  Skipping — no data returned")
        continue

    raw.columns = [col[0] if isinstance(col, tuple) else col for col in raw.columns]
    data        = add_indicators(raw)
    features    = data[FEATURES]

    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(features)

    X, y = [], []
    for i in range(WINDOW, len(scaled)):
        X.append(scaled[i - WINDOW:i])
        y.append(scaled[i, 0])

    X = np.array(X)
    y = np.array(y)

    print(f"  Samples: {len(X)}")

    model = build_model((X.shape[1], X.shape[2]))
    model.fit(X, y, epochs=EPOCHS, batch_size=BATCH, verbose=1)

    model.save_weights(f"models/{ticker}_model.weights.h5")
    pickle.dump(scaler, open(f"scalers/{ticker}_scaler.pkl", "wb"))

    print(f"  Saved: models/{ticker}_model.weights.h5")
    print(f"  Saved: scalers/{ticker}_scaler.pkl")

print("\n All 10 models trained and saved.")
print(" Now upload the models/ and scalers/ folders to GitHub.")

